DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE groups (id SERIAL NOT NULL PRIMARY KEY UNIQUE, name VARCHAR UNIQUE);
DROP TABLE IF EXISTS students;
DROP TYPE IF EXISTS genderEnum;
CREATE TYPE genderEnum AS ENUM ('MALE', 'FAMALE');
CREATE TABLE students (id SERIAL NOT NULL PRIMARY KEY UNIQUE, name VARCHAR, surename VARCHAR, date_of_birth DATE, gender VARCHAR, group_id SERIAL REFERENCES groups(id) ON DELETE SET NULL);